version: '3'

services:
  app:
    build: .
    container_name: sistema_inventario
    ports:
      - "5000:5000"
    volumes:
      - ./inventario.json:/app/inventario.json
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped